# Generated by Django 4.1.6 on 2023-02-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_user_type_remove_teacher_teacher_delete_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_type',
            old_name='is_teach',
            new_name='is_teacher',
        ),
    ]
